feat: make model customizable
embedchain/embedchainjs pull request #29
Opened 2023-07-21 19:29 UTC by jonasiwnl

just a note -- this change requires that model is not a static property of the EmbedChain class, but rather a field of an instance. As a result, the functions getOpenAiAnswer and getAnswerFromLLM are no longer static, but methods on an instance.

2023-07-23 08:50 UTC, cachho requested changes

2023-07-23 08:50 UTC, cachho commented on embedchain/embedchain.ts
> +      this.model = appConfig.model;
With this, there's no default model, right? We do need a default model, to not make this change breaking.

2023-07-23 08:50 UTC, cachho commented
And AppConfig is just a type, not a class. We have to see in what way we copy that from Python, there it's a class but TS gives us different options. But that doesn't have to be done in this PR.

2023-07-24 00:00 UTC, jonasiwnl commented on embedchain/embedchain.ts
> +      this.model = appConfig.model;
default is 'gpt-3.5-turbo', set on line 40. if a model is defined in the config it changes the model to that, but if not, it says as the default value

2023-07-24 00:03 UTC, jonasiwnl commented
AppConfig doesn't require state, so personally I don't think a class would be useful.

2023-09-05 05:08 UTC, taranjeet commented
Closing this pull request. We will address this issue in a different way.

2023-09-05 05:09 UTC, closed without merging